# Generated by Django 3.1.5 on 2021-01-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidtransaction',
            name='create_time',
            field=models.PositiveBigIntegerField(),
        ),
    ]
