# Generated by Django 3.1.5 on 2021-01-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidapp', '0002_auto_20210130_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biditem',
            name='id',
        ),
        migrations.AlterField(
            model_name='biditem',
            name='item_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
