# Generated by Django 3.1.5 on 2021-01-30 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidapp', '0003_auto_20210130_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='token',
            new_name='token_balance',
        ),
    ]
