# Generated by Django 3.1.5 on 2021-01-30 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidapp', '0004_auto_20210130_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unseen_noti_no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('create_time', models.PositiveBigIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidapp.biditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidapp.user')),
            ],
        ),
    ]
